[build]
  command = "npm install && npm run build"
  publish = "dist"
  node-version = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_TOKEN = "obxjwamoarzzzddmhpke"