[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "10.2.4"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_TOKEN = "obxjwamoarzzzddmhpke"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200